In [1]:
from pyspark.sql import  SparkSession

# Saprksession

In [2]:
spark = SparkSession.builder.appName('dataframe').getOrCreate()

In [3]:
df = spark.read.options(inferschema=True).csv('data/StudentData.csv',header=True)

In [4]:
#df.show()
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [73]:
from pyspark.sql.types import StructField,StringType,IntegerType,StructType

schema = StructType([
        StructField('Age',IntegerType(),True),
        StructField('gender',StringType(),True),
        StructField('name',StringType(),True),
        StructField('course',StringType(),True),
        StructField('roll',StringType(),True),
        StructField('marks',IntegerType(),True), 
        StructField('email',StringType(),True )

])

In [74]:
# provide our schema
df = spark.read.options(header=True).schema(schema).csv('data/StudentData.csv')

In [17]:
df.show(
    
)

+---+------+----------------+------+------+-----+
|Age|gender|            name|course|  roll|marks|
+---+------+----------------+------+------+-----+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|
| 29|Female|    Elenore Choy|    DB| 32877|   29|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|
| 28|Female|    Claude Panos| Cloud| 72409|   85|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|
| 29|Female|       Kena Wild|   DSA|102285|   35|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|
| 29|  Male|     Neda Briski|    PF|141770|   42|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|
| 28|Female|Mickey Cortright|    DB|192537|   62|
+---+------+----------------+------+------+-----+
only showing top 20 rows

In [18]:
df.printSchema()

root
 |-- Age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)

# RDD to DATAFrame

In [22]:
from pyspark import SparkConf,SparkContext

conf = SparkConf().setAppName('data')
sc = SparkContext.getOrCreate()

In [59]:
rdd = sc.textFile('data/StudentData.csv')

In [60]:
head = rdd.first()
rdd = rdd.filter(lambda x : x!=head).map(lambda x: x.split(','))
rdd = rdd.map(lambda x : [int(x[0]), x[1], x[2], x[3], x[4], int(x[5]), x[6]])

In [61]:
rdd.collect()

[[28,
  'Female',
  'Hubert Oliveras',
  'DB',
  '02984',
  59,
  'Annika Hoffman_Naoma Fritts@OOP.com'],
 [29,
  'Female',
  'Toshiko Hillyard',
  'Cloud',
  '12899',
  62,
  'Margene Moores_Marylee Capasso@DB.com'],
 [28,
  'Male',
  'Celeste Lollis',
  'PF',
  '21267',
  45,
  'Jeannetta Golden_Jenna Montague@DSA.com'],
 [29,
  'Female',
  'Elenore Choy',
  'DB',
  '32877',
  29,
  'Billi Clore_Mitzi Seldon@DB.com'],
 [28,
  'Male',
  'Sheryll Towler',
  'DSA',
  '41487',
  41,
  'Claude Panos_Judie Chipps@OOP.com'],
 [28,
  'Male',
  'Margene Moores',
  'MVC',
  '52771',
  32,
  'Toshiko Hillyard_Clementina Menke@MVC.com'],
 [28,
  'Male',
  'Neda Briski',
  'OOP',
  '61973',
  69,
  'Alberta Freund_Elenore Choy@DB.com'],
 [28,
  'Female',
  'Claude Panos',
  'Cloud',
  '72409',
  85,
  'Sheryll Towler_Alberta Freund@Cloud.com'],
 [28,
  'Male',
  'Celeste Lollis',
  'MVC',
  '81492',
  64,
  'Nicole Harwood_Claude Panos@MVC.com'],
 [29,
  'Male',
  'Cordie Harnois',
  'OOP',
  '92882',
  51,
  'Judie Chipps_Clementina Menke@MVC.com'],
 [29,
  'Female',
  'Kena Wild',
  'DSA',
  '102285',
  35,
  'Dustin Feagins_Margene Moores@OOP.com'],
 [29,
  'Male',
  'Ernest Rossbach',
  'DB',
  '111449',
  53,
  'Maybell Duguay_Abram Nagao@OOP.com'],
 [28,
  'Female',
  'Latia Vanhoose',
  'DB',
  '122502',
  27,
  'Latia Vanhoose_Mitzi Seldon@OOP.com'],
 [29,
  'Female',
  'Latia Vanhoose',
  'MVC',
  '132110',
  55,
  'Eda Neathery_Nicole Harwood@Cloud.com'],
 [29,
  'Male',
  'Neda Briski',
  'PF',
  '141770',
  42,
  'Margene Moores_Michelle Ruggiero@MVC.com'],
 [29,
  'Female',
  'Latia Vanhoose',
  'DB',
  '152159',
  27,
  'Claude Panos_Santa Kerfien@DB.com'],
 [29,
  'Male',
  'Loris Crossett',
  'MVC',
  '161771',
  36,
  'Mitzi Seldon_Jenna Montague@MVC.com'],
 [29,
  'Male',
  'Annika Hoffman',
  'OOP',
  '171660',
  22,
  'Taryn Brownlee_Mitzi Seldon@MVC.com'],
 [29,
  'Male',
  'Santa Kerfien',
  'PF',
  '182129',
  56,
  'Judie Chipps_Taryn Brownlee@Cloud.com'],
 [28,
  'Female',
  'Mickey Cortright',
  'DB',
  '192537',
  62,
  'Ernest Rossbach_Marylee Capasso@Cloud.com'],
 [29,
  'Female',
  'Loris Crossett',
  'PF',
  '201487',
  96,
  'Elenore Choy_Latia Vanhoose@Cloud.com'],
 [29,
  'Female',
  'Niki Klimek',
  'PF',
  '211508',
  23,
  'Cordie Harnois_Judie Chipps@PF.com'],
 [28,
  'Female',
  'Kena Wild',
  'Cloud',
  '221750',
  60,
  'Mitzi Seldon_Jenna Montague@DSA.com'],
 [28,
  'Female',
  'Jc Andrepont',
  'DSA',
  '232060',
  58,
  'Billi Clore_Abram Nagao@MVC.com'],
 [29,
  'Female',
  'Anna Santos',
  'Cloud',
  '242254',
  68,
  'Jc Andrepont_Hubert Oliveras@Cloud.com'],
 [28,
  'Female',
  'Alberta Freund',
  'OOP',
  '251805',
  83,
  'Annika Hoffman_Sheryll Towler@MVC.com'],
 [28,
  'Female',
  'Maybell Duguay',
  'Cloud',
  '261439',
  20,
  'Nicole Harwood_Judie Chipps@DB.com'],
 [29,
  'Female',
  'Paris Hutton',
  'DSA',
  '271472',
  99,
  'Sheryll Towler_Alberta Freund@DSA.com'],
 [29,
  'Female',
  'Cheri Kenney',
  'Cloud',
  '281408',
  43,
  'Annika Hoffman_Melani Engberg@Cloud.com'],
 [28,
  'Female',
  'Dustin Feagins',
  'DSA',
  '291984',
  82,
  'Abram Nagao_Kena Wild@Cloud.com'],
 [29,
  'Female',
  'Claude Panos',
  'Cloud',
  '302130',
  59,
  'Sheryll Towler_Leontine Phillips@PF.com'],
 [28,
  'Female',
  'Anna Santos',
  'DB',
  '311589',
  79,
  'Celeste Lollis_Mickey Cortright@DSA.com'],
 [28,
  'Female',
  'Cheri Kenney',
  'MVC',
  '321816',
  24,
  'Kena Wild_Michelle Ruggiero@DB.com'],
 [28,
  'Female',
  'Loris Crossett',
  'PF',
  '332739',
  62,
  'Michelle Ruggiero_Clementina Menke@DB.com'],
 [28,
  'Female',
  'Mickey Cortright',
  'DSA',
  '342003',
  44,
  'Mitzi Seldon_Jeannetta Golden@PF.com'],
 [28,
  'Male',
  'Hubert Oliveras',
  'OOP',
  '351719',
  63,
  'Lawanda Wohlwend_Abram Nagao@MVC.com'],
 [28,
  'Male',
  'Sebrina Maresca',
  'PF',
  '361316',
  62,
  'Nicole Harwood_Latia Vanhoose@DB.com'],
 [29,
  'Male',
  'Jalisa Swenson',
  'PF',
  '372873',
  45,
  'Ernest Rossbach_Toshiko Hillyard@DB.com'],
 [28,
  'Male',
  'Kizzy Brenner',
  'DB',
  '381712',
  36,
  'Paris Hutton_Kena Wild@MVC.com'],
 [28,
  'Male',
  'Toshiko Hillyard',
  'DB',
  '392218',
  47,
  'Leontine Phillips_Billi Clore@MVC.com'],
 [28,
  'Female',
  'Kizzy Brenner',
  'Cloud',
  '402409',
  27,
  'Ernest Rossbach_Gonzalo Ferebee@OOP.com'],
 [29,
  'Female',
  'Anna Santos',
  'DSA',
  '411479',
  42,
  'Kena Wild_Mitzi Seldon@DB.com'],
 [28,
  'Male',
  'Elenore Choy',
  'PF',
  '422704',
  66,
  'Marylee Capasso_Nicole Harwood@MVC.com'],
 [28,
  'Female',
  'Jalisa Swenson',
  'OOP',
  '431352',
  25,
  'Gonzalo Ferebee_Judie Chipps@DB.com'],
 [29,
  'Female',
  'Somer Stoecker',
  'Cloud',
  '442028',
  34,
  'Taryn Brownlee_Taryn Brownlee@MVC.com'],
 [28,
  'Female',
  'Maybell Duguay',
  'DSA',
  '452141',
  29,
  'Leontine Phillips_Elenore Choy@Cloud.com'],
 [28,
  'Male',
  'Dustin Feagins',
  'PF',
  '461839',
  51,
  'Neda Briski_Elenore Choy@Cloud.com'],
 [29,
  'Male',
  'Annika Hoffman',
  'OOP',
  '472550',
  35,
  'Mitzi Seldon_Abram Nagao@DSA.com'],
 [29,
  'Male',
  'Paris Hutton',
  'DB',
  '481229',
  57,
  'Clementina Menke_Paris Hutton@MVC.com'],
 [29,
  'Female',
  'Paris Hutton',
  'DSA',
  '492159',
  60,
  'Nicole Harwood_Marylee Capasso@OOP.com'],
 [29,
  'Female',
  'Jenna Montague',
  'MVC',
  '502585',
  43,
  'Hubert Oliveras_Jc Andrepont@DSA.com'],
 [29,
  'Male',
  'Billi Clore',
  'Cloud',
  '512047',
  76,
  'Taryn Brownlee_Judie Chipps@DSA.com'],
 [29,
  'Male',
  'Toshiko Hillyard',
  'OOP',
  '521221',
  77,
  'Hubert Oliveras_Latia Vanhoose@MVC.com'],
 [28,
  'Male',
  'Margene Moores',
  'PF',
  '531530',
  53,
  'Cheri Kenney_Melani Engberg@OOP.com'],
 [29,
  'Female',
  'Claude Panos',
  'OOP',
  '542821',
  28,
  'Hubert Oliveras_Priscila Tavernier@PF.com'],
 [28,
  'Female',
  'Mickey Cortright',
  'DB',
  '551389',
  43,
  'Tijuana Kropf_Jenna Montague@DB.com'],
 [29,
  'Male',
  'Celeste Lollis',
  'DSA',
  '562065',
  85,
  'Jc Andrepont_Melani Engberg@OOP.com'],
 [28,
  'Female',
  'Tijuana Kropf',
  'PF',
  '571047',
  41,
  'Loris Crossett_Sebrina Maresca@PF.com'],
 [28,
  'Male',
  'Marylee Capasso',
  'OOP',
  '581756',
  52,
  'Jeannetta Golden_Loris Crossett@MVC.com'],
 [29,
  'Male',
  'Maybell Duguay',
  'DSA',
  '592061',
  83,
  'Eda Neathery_Jenna Montague@Cloud.com'],
 [28,
  'Female',
  'Leontine Phillips',
  'DB',
  '602404',
  48,
  'Neda Briski_Cheri Kenney@PF.com'],
 [28,
  'Female',
  'Somer Stoecker',
  'Cloud',
  '612490',
  82,
  'Sebrina Maresca_Gonzalo Ferebee@DSA.com'],
 [28,
  'Male',
  'Mitzi Seldon',
  'DSA',
  '622981',
  45,
  'Lawanda Wohlwend_Loris Crossett@DSA.com'],
 [29,
  'Female',
  'Judie Chipps',
  'Cloud',
  '632793',
  75,
  'Tijuana Kropf_Elenore Choy@PF.com'],
 [28,
  'Male',
  'Priscila Tavernier',
  'PF',
  '642594',
  27,
  'Marylee Capasso_Claude Panos@DSA.com'],
 [29,
  'Male',
  'Tamera Blakley',
  'MVC',
  '651649',
  92,
  'Latia Vanhoose_Toshiko Hillyard@MVC.com'],
 [28,
  'Male',
  'Sheryll Towler',
  'MVC',
  '661079',
  89,
  'Tijuana Kropf_Mickey Cortright@DB.com'],
 [29,
  'Male',
  'Hubert Oliveras',
  'MVC',
  '672451',
  28,
  'Annika Hoffman_Mickey Cortright@DSA.com'],
 [29,
  'Male',
  'Sheryll Towler',
  'PF',
  '682533',
  42,
  'Billi Clore_Anna Santos@PF.com'],
 [28,
  'Female',
  'Jenna Montague',
  'DSA',
  '691564',
  26,
  'Mitzi Seldon_Sebrina Maresca@Cloud.com'],
 [29,
  'Male',
  'Maybell Duguay',
  'PF',
  '701486',
  99,
  'Clementina Menke_Latia Vanhoose@Cloud.com'],
 [29,
  'Male',
  'Jenna Montague',
  'MVC',
  '711153',
  45,
  'Marylee Capasso_Hubert Oliveras@DB.com'],
 [28,
  'Male',
  'Annika Hoffman',
  'Cloud',
  '722193',
  55,
  'Taryn Brownlee_Elenore Choy@DB.com'],
 [28,
  'Female',
  'Celeste Lollis',
  'DSA',
  '731879',
  76,
  'Hubert Oliveras_Gonzalo Ferebee@DSA.com'],
 [29,
  'Male',
  'Jeannetta Golden',
  'MVC',
  '741875',
  57,
  'Sheryll Towler_Cheri Kenney@DSA.com'],
 [29,
  'Male',
  'Paris Hutton',
  'MVC',
  '752504',
  22,
  'Elenore Choy_Elenore Choy@DB.com'],
 [29,
  'Female',
  'Margene Moores',
  'MVC',
  '761843',
  48,
  'Ernest Rossbach_Mickey Cortright@DSA.com'],
 [28,
  'Female',
  'Hubert Oliveras',
  'DB',
  '771081',
  79,
  'Kizzy Brenner_Dustin Feagins@MVC.com'],
 [28,
  'Male',
  'Alberta Freund',
  'PF',
  '781061',
  75,
  'Leontine Phillips_Bonita Higuera@PF.com'],
 [29,
  'Female',
  'Billi Clore',
  'OOP',
  '791519',
  93,
  'Elenore Choy_Jalisa Swenson@MVC.com'],
 [28,
  'Female',
  'Billi Clore',
  'Cloud',
  '801693',
  38,
  'Niki Klimek_Kizzy Brenner@DB.com'],
 [29,
  'Female',
  'Elenore Choy',
  'DB',
  '811824',
  55,
  'Maybell Duguay_Melani Engberg@DB.com'],
 [28,
  'Male',
  'Anna Santos',
  'OOP',
  '822396',
  47,
  'Leontine Phillips_Gonzalo Ferebee@Cloud.com'],
 [28,
  'Male',
  'Sheryll Towler',
  'DSA',
  '831562',
  59,
  'Kena Wild_Gonzalo Ferebee@Cloud.com'],
 [29,
  'Male',
  'Neda Briski',
  'PF',
  '842515',
  68,
  'Neda Briski_Hubert Oliveras@OOP.com'],
 [28,
  'Female',
  'Santa Kerfien',
  'Cloud',
  '851620',
  34,
  'Melani Engberg_Sheryll Towler@PF.com'],
 [29,
  'Female',
  'Taryn Brownlee',
  'MVC',
  '861849',
  39,
  'Billi Clore_Toshiko Hillyard@MVC.com'],
 [28,
  'Female',
  'Sheryll Towler',
  'DSA',
  '871967',
  64,
  'Michelle Ruggiero_Billi Clore@Cloud.com'],
 [29,
  'Male',
  'Clementina Menke',
  'DB',
  '882200',
  76,
  'Michelle Ruggiero_Jenna Montague@MVC.com'],
 [28,
  'Male',
  'Margene Moores',
  'DSA',
  '892010',
  93,
  'Anna Santos_Naoma Fritts@DSA.com'],
 [28,
  'Female',
  'Somer Stoecker',
  'DSA',
  '901958',
  64,
  'Kizzy Brenner_Jc Andrepont@DB.com'],
 [29,
  'Male',
  'Loris Crossett',
  'PF',
  '911593',
  46,
  'Gonzalo Ferebee_Mitzi Seldon@PF.com'],
 [29,
  'Female',
  'Sebrina Maresca',
  'DB',
  '922210',
  54,
  'Toshiko Hillyard_Santa Kerfien@MVC.com'],
 [29,
  'Male',
  'Naoma Fritts',
  'DB',
  '931295',
  79,
  'Hubert Oliveras_Sheryll Towler@DSA.com'],
 [28,
  'Female',
  'Santa Kerfien',
  'MVC',
  '941783',
  94,
  'Paris Hutton_Naoma Fritts@DB.com'],
 [28,
  'Female',
  'Lawanda Wohlwend',
  'DSA',
  '951686',
  60,
  'Loris Crossett_Nicole Harwood@DSA.com'],
 [29,
  'Male',
  'Abram Nagao',
  'MVC',
  '962235',
  32,
  'Jenna Montague_Gonzalo Ferebee@DSA.com'],
 [28,
  'Female',
  'Jc Andrepont',
  'PF',
  '972733',
  20,
  'Eda Neathery_Eda Neathery@MVC.com'],
 [29,
  'Male',
  'Niki Klimek',
  'PF',
  '982443',
  94,
  'Santa Kerfien_Kizzy Brenner@DB.com'],
 [28,
  'Female',
  'Marylee Capasso',
  'OOP',
  '991770',
  86,
  'Margene Moores_Clementina Menke@DB.com'],
 [28,
  'Male',
  'Jenna Montague',
  'DSA',
  '1002103',
  36,
  'Melani Engberg_Hubert Oliveras@PF.com'],
 [29,
  'Female',
  'Eda Neathery',
  'Cloud',
  '1011971',
  91,
  'Margene Moores_Elenore Choy@MVC.com'],
 [29,
  'Male',
  'Michelle Ruggiero',
  'DSA',
  '1022971',
  99,
  'Cordie Harnois_Clementina Menke@OOP.com'],
 [28,
  'Male',
  'Annika Hoffman',
  'DB',
  '1031544',
  44,
  'Dustin Feagins_Somer Stoecker@DB.com'],
 [29,
  'Female',
  'Hubert Oliveras',
  'DSA',
  '1041483',
  28,
  'Billi Clore_Santa Kerfien@DSA.com'],
 [28,
  'Male',
  'Billi Clore',
  'MVC',
  '1052566',
  78,
  'Naoma Fritts_Margene Moores@DSA.com'],
 [28,
  'Female',
  'Nicole Harwood',
  'MVC',
  '1061068',
  82,
  'Santa Kerfien_Hubert Oliveras@MVC.com'],
 [29,
  'Male',
  'Clementina Menke',
  'PF',
  '1071717',
  54,
  'Celeste Lollis_Leontine Phillips@OOP.com'],
 [28,
  'Female',
  'Claude Panos',
  'OOP',
  '1081294',
  94,
  'Kizzy Brenner_Anna Santos@OOP.com'],
 [29,
  'Male',
  'Donna Yerby',
  'DSA',
  '1092702',
  79,
  'Marylee Capasso_Alberta Freund@OOP.com'],
 [29,
  'Female',
  'Maybell Duguay',
  'MVC',
  '1102536',
  22,
  'Somer Stoecker_Marylee Capasso@OOP.com'],
 [29,
  'Male',
  'Abram Nagao',
  'PF',
  '1112161',
  42,
  'Nicole Harwood_Niki Klimek@DB.com'],
 [28,
  'Female',
  'Bonita Higuera',
  'DSA',
  '1122348',
  51,
  'Somer Stoecker_Jenna Montague@DB.com'],
 [29,
  'Female',
  'Melani Engberg',
  'OOP',
  '1132093',
  76,
  'Kena Wild_Neda Briski@Cloud.com'],
 [29,
  'Female',
  'Marylee Capasso',
  'OOP',
  '1142653',
  61,
  'Cordie Harnois_Alberta Freund@DSA.com'],
 [29,
  'Male',
  'Nicole Harwood',
  'Cloud',
  '1152571',
  62,
  'Latia Vanhoose_Maybell Duguay@PF.com'],
 [29,
  'Female',
  'Dustin Feagins',
  'OOP',
  '1161607',
  37,
  'Eda Neathery_Marylee Capasso@MVC.com'],
 [28,
  'Female',
  'Niki Klimek',
  'PF',
  '1172784',
  24,
  'Jeannetta Golden_Abram Nagao@MVC.com'],
 [29,
  'Female',
  'Abram Nagao',
  'DSA',
  '1181007',
  57,
  'Anna Santos_Anna Santos@DSA.com'],
 [28,
  'Male',
  'Jalisa Swenson',
  'PF',
  '1192555',
  77,
  'Marylee Capasso_Celeste Lollis@Cloud.com'],
 [29,
  'Female',
  'Ernest Rossbach',
  'MVC',
  '1201427',
  80,
  'Elenore Choy_Jenna Montague@OOP.com'],
 [28,
  'Male',
  'Nicole Harwood',
  'DB',
  '1211495',
  28,
  'Melani Engberg_Jc Andrepont@Cloud.com'],
 [29,
  'Female',
  'Claude Panos',
  'DB',
  '1222887',
  75,
  'Hubert Oliveras_Somer Stoecker@Cloud.com'],
 [28,
  'Female',
  'Cordie Harnois',
  'OOP',
  '1231943',
  68,
  'Mickey Cortright_Kizzy Brenner@OOP.com'],
 [28,
  'Male',
  'Nicole Harwood',
  'OOP',
  '1242426',
  71,
  'Billi Clore_Loris Crossett@Cloud.com'],
 [28,
  'Male',
  'Gonzalo Ferebee',
  'Cloud',
  '1251176',
  60,
  'Santa Kerfien_Tamera Blakley@PF.com'],
 [29,
  'Male',
  'Jalisa Swenson',
  'Cloud',
  '1261533',
  70,
  'Dustin Feagins_Nicole Harwood@PF.com'],
 [28,
  'Female',
  'Eda Neathery',
  'Cloud',
  '1272870',
  69,
  'Somer Stoecker_Dustin Feagins@DB.com'],
 [28,
  'Female',
  'Toshiko Hillyard',
  'DSA',
  '1282835',
  79,
  'Somer Stoecker_Toshiko Hillyard@OOP.com'],
 [28,
  'Male',
  'Paris Hutton',
  'MVC',
  '1292279',
  26,
  'Paris Hutton_Eda Neathery@DSA.com'],
 [29,
  'Female',
  'Niki Klimek',
  'DB',
  '1301784',
  24,
  'Celeste Lollis_Tamera Blakley@DB.com'],
 [28,
  'Male',
  'Bonita Higuera',
  'Cloud',
  '1312294',
  94,
  'Eda Neathery_Priscila Tavernier@PF.com'],
 [28,
  'Female',
  'Leontine Phillips',
  'MVC',
  '1322629',
  87,
  'Judie Chipps_Michelle Ruggiero@Cloud.com'],
 [29,
  'Male',
  'Jalisa Swenson',
  'PF',
  '1332072',
  88,
  'Billi Clore_Kizzy Brenner@Cloud.com'],
 [28,
  'Male',
  'Clementina Menke',
  'OOP',
  '1341574',
  46,
  'Elenore Choy_Mickey Cortright@DB.com'],
 [28,
  'Male',
  'Gonzalo Ferebee',
  'PF',
  '1352348',
  95,
  'Neda Briski_Somer Stoecker@DB.com'],
 [29,
  'Female',
  'Jalisa Swenson',
  'DSA',
  '1362151',
  51,
  'Lawanda Wohlwend_Jenna Montague@PF.com'],
 [28,
  'Male',
  'Lawanda Wohlwend',
  'PF',
  '1372552',
  88,
  'Hubert Oliveras_Tijuana Kropf@DSA.com'],
 [28,
  'Male',
  'Abram Nagao',
  'DSA',
  '1382959',
  66,
  'Michelle Ruggiero_Kena Wild@OOP.com'],
 [29,
  'Female',
  'Hubert Oliveras',
  'Cloud',
  '1392791',
  94,
  'Anna Santos_Alberta Freund@Cloud.com'],
 [28,
  'Male',
  'Bonita Higuera',
  'Cloud',
  '1401526',
  24,
  'Jc Andrepont_Cheri Kenney@Cloud.com'],
 [29,
  'Female',
  'Clementina Menke',
  'OOP',
  '1412376',
  65,
  'Elenore Choy_Latia Vanhoose@DSA.com'],
 [29,
  'Female',
  'Mickey Cortright',
  'Cloud',
  '1421542',
  71,
  'Latia Vanhoose_Kena Wild@OOP.com'],
 [29,
  'Female',
  'Leontine Phillips',
  'DB',
  '1432252',
  67,
  'Billi Clore_Sheryll Towler@DB.com'],
 [28,
  'Female',
  'Nicole Harwood',
  'PF',
  '1441367',
  95,
  'Jc Andrepont_Anna Santos@DSA.com'],
 [28,
  'Female',
  'Gonzalo Ferebee',
  'DB',
  '1451513',
  69,
  'Claude Panos_Tamera Blakley@PF.com'],
 [29,
  'Female',
  'Judie Chipps',
  'DB',
  '1461078',
  31,
  'Tijuana Kropf_Billi Clore@OOP.com'],
 [29,
  'Male',
  'Niki Klimek',
  'MVC',
  '1472917',
  36,
  'Sebrina Maresca_Sheryll Towler@MVC.com'],
 [29,
  'Female',
  'Lawanda Wohlwend',
  'MVC',
  '1482889',
  65,
  'Gonzalo Ferebee_Dustin Feagins@PF.com'],
 [28,
  'Male',
  'Jc Andrepont',
  'DSA',
  '1492828',
  78,
  'Celeste Lollis_Kizzy Brenner@MVC.com'],
 [28,
  'Female',
  'Cordie Harnois',
  'MVC',
  '1501333',
  94,
  'Gonzalo Ferebee_Tijuana Kropf@OOP.com'],
 [29,
  'Female',
  'Taryn Brownlee',
  'OOP',
  '1511213',
  72,
  'Cheri Kenney_Donna Yerby@DSA.com'],
 [28,
  'Male',
  'Hubert Oliveras',
  'PF',
  '1521724',
  91,
  'Eda Neathery_Jeannetta Golden@MVC.com'],
 [29,
  'Female',
  'Naoma Fritts',
  'MVC',
  '1532260',
  73,
  'Elenore Choy_Judie Chipps@DSA.com'],
 [28,
  'Female',
  'Marylee Capasso',
  'Cloud',
  '1541030',
  58,
  'Cordie Harnois_Celeste Lollis@PF.com'],
 [29,
  'Female',
  'Annika Hoffman',
  'OOP',
  '1551846',
  50,
  'Paris Hutton_Melani Engberg@DB.com'],
 [28,
  'Female',
  'Jeannetta Golden',
  'OOP',
  '1562758',
  40,
  'Jeannetta Golden_Billi Clore@Cloud.com'],
 [29,
  'Female',
  'Cheri Kenney',
  'MVC',
  '1571310',
  88,
  'Cordie Harnois_Lawanda Wohlwend@MVC.com'],
 [29,
  'Female',
  'Jeannetta Golden',
  'PF',
  '1581770',
  39,
  'Bonita Higuera_Santa Kerfien@OOP.com'],
 [28,
  'Female',
  'Tamera Blakley',
  'PF',
  '1591554',
  78,
  'Sebrina Maresca_Tijuana Kropf@OOP.com'],
 [28,
  'Male',
  'Paris Hutton',
  'MVC',
  '1602777',
  53,
  'Sheryll Towler_Loris Crossett@DSA.com'],
 [28,
  'Male',
  'Marylee Capasso',
  'DB',
  '1611411',
  96,
  'Annika Hoffman_Loris Crossett@PF.com'],
 [28,
  'Male',
  'Anna Santos',
  'OOP',
  '1621905',
  24,
  'Elenore Choy_Santa Kerfien@DB.com'],
 [28,
  'Male',
  'Neda Briski',
  'DSA',
  '1632185',
  93,
  'Clementina Menke_Toshiko Hillyard@Cloud.com'],
 [29,
  'Female',
  'Michelle Ruggiero',
  'DB',
  '1642509',
  45,
  'Hubert Oliveras_Marylee Capasso@DB.com'],
 [28,
  'Female',
  'Neda Briski',
  'Cloud',
  '1651303',
  74,
  'Ernest Rossbach_Donna Yerby@OOP.com'],
 [28,
  'Female',
  'Loris Crossett',
  'DSA',
  '1662549',
  86,
  'Paris Hutton_Latia Vanhoose@Cloud.com'],
 [29,
  'Male',
  'Alberta Freund',
  'DB',
  '1671638',
  98,
  'Clementina Menke_Jalisa Swenson@Cloud.com'],
 [28,
  'Female',
  'Sebrina Maresca',
  'MVC',
  '1681804',
  27,
  'Celeste Lollis_Ernest Rossbach@MVC.com'],
 [28,
  'Male',
  'Celeste Lollis',
  'DB',
  '1692106',
  36,
  'Neda Briski_Abram Nagao@MVC.com'],
 [29,
  'Female',
  'Anna Santos',
  'DSA',
  '1702439',
  64,
  'Naoma Fritts_Toshiko Hillyard@DB.com'],
 [28,
  'Female',
  'Margene Moores',
  'DSA',
  '1712967',
  41,
  'Tijuana Kropf_Sheryll Towler@DB.com'],
 [28,
  'Female',
  'Priscila Tavernier',
  'DB',
  '1722388',
  86,
  'Lawanda Wohlwend_Loris Crossett@DSA.com'],
 [29,
  'Female',
  'Jc Andrepont',
  'MVC',
  '1731652',
  74,
  'Hubert Oliveras_Michelle Ruggiero@DSA.com'],
 [28,
  'Female',
  'Anna Santos',
  'DSA',
  '1741879',
  89,
  'Nicole Harwood_Lawanda Wohlwend@DB.com'],
 [29,
  'Female',
  'Lawanda Wohlwend',
  'MVC',
  '1751381',
  75,
  'Jalisa Swenson_Nicole Harwood@OOP.com'],
 [29,
  'Male',
  'Nicole Harwood',
  'MVC',
  '1761454',
  34,
  'Taryn Brownlee_Billi Clore@DSA.com'],
 [29,
  'Male',
  'Claude Panos',
  'DSA',
  '1771605',
  50,
  'Claude Panos_Tamera Blakley@OOP.com'],
 [29,
  'Male',
  'Dustin Feagins',
  'DB',
  '1782045',
  81,
  'Cordie Harnois_Toshiko Hillyard@OOP.com'],
 [29,
  'Male',
  'Toshiko Hillyard',
  'DSA',
  '1791364',
  50,
  'Jc Andrepont_Nicole Harwood@MVC.com'],
 [28,
  'Male',
  'Alberta Freund',
  'Cloud',
  '1802934',
  24,
  'Maybell Duguay_Paris Hutton@PF.com'],
 [29,
  'Female',
  'Tijuana Kropf',
  'MVC',
  '1811192',
  51,
  'Anna Santos_Latia Vanhoose@DSA.com'],
 [29,
  'Female',
  'Ernest Rossbach',
  'Cloud',
  '1821977',
  28,
  'Annika Hoffman_Kizzy Brenner@DSA.com'],
 [29,
  'Male',
  'Latia Vanhoose',
  'Cloud',
  '1832268',
  60,
  'Marylee Capasso_Santa Kerfien@MVC.com'],
 [29,
  'Male',
  'Alberta Freund',
  'OOP',
  '1841931',
  37,
  'Jenna Montague_Taryn Brownlee@Cloud.com'],
 [28,
  'Female',
  'Lawanda Wohlwend',
  'DB',
  '1852072',
  30,
  'Bonita Higuera_Jenna Montague@DB.com'],
 [29,
  'Male',
  'Celeste Lollis',
  'PF',

In [62]:
col = head.split(',')
col

['age', 'gender', 'name', 'course', 'roll', 'marks', 'email']

In [63]:
df1 = rdd.toDF(col )

In [64]:
df1.printSchema()

root
 |-- age: long (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: long (nullable = true)
 |-- email: string (nullable = true)

In [65]:
df1.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [75]:
df2 = spark.createDataFrame(rdd,schema=schema)

In [76]:
df2.printSchema()

root
 |-- Age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [77]:
df2.show()

+---+------+----------------+------+------+-----+--------------------+
|Age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

# Select and withColumn

In [81]:
df.select('Age','gender').show()

+---+------+
|Age|gender|
+---+------+
| 28|Female|
| 29|Female|
| 28|  Male|
| 29|Female|
| 28|  Male|
| 28|  Male|
| 28|  Male|
| 28|Female|
| 28|  Male|
| 29|  Male|
| 29|Female|
| 29|  Male|
| 28|Female|
| 29|Female|
| 29|  Male|
| 29|Female|
| 29|  Male|
| 29|  Male|
| 29|  Male|
| 28|Female|
+---+------+
only showing top 20 rows

In [83]:
from pyspark.sql.functions import col 
df.select(col('Age'),col('name')).show()

+---+----------------+
|Age|            name|
+---+----------------+
| 28| Hubert Oliveras|
| 29|Toshiko Hillyard|
| 28|  Celeste Lollis|
| 29|    Elenore Choy|
| 28|  Sheryll Towler|
| 28|  Margene Moores|
| 28|     Neda Briski|
| 28|    Claude Panos|
| 28|  Celeste Lollis|
| 29|  Cordie Harnois|
| 29|       Kena Wild|
| 29| Ernest Rossbach|
| 28|  Latia Vanhoose|
| 29|  Latia Vanhoose|
| 29|     Neda Briski|
| 29|  Latia Vanhoose|
| 29|  Loris Crossett|
| 29|  Annika Hoffman|
| 29|   Santa Kerfien|
| 28|Mickey Cortright|
+---+----------------+
only showing top 20 rows

In [87]:
df.withColumn('updated_mark',col('marks')+30).show()

+---+------+----------------+------+------+-----+--------------------+------------+
|Age|gender|            name|course|  roll|marks|               email|updated_mark|
+---+------+----------------+------+------+-----+--------------------+------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|          89|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|          92|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|          75|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|          59|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|          71|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|          62|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|          99|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|         115|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|          94|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|          81|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|          65|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|          83|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|          57|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|          85|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|          72|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|          57|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|          66|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|          52|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|          86|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|          92|
+---+------+----------------+------+------+-----+--------------------+------------+
only showing top 20 rows

In [88]:
# rename column
df.withColumnRenamed('gender','sex').withColumnRenamed('name','full_name').show()

+---+------+----------------+------+------+-----+--------------------+
|Age|   sex|       full_name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [90]:
df.select(col('name').alias('full_name')).show()

+----------------+
|       full_name|
+----------------+
| Hubert Oliveras|
|Toshiko Hillyard|
|  Celeste Lollis|
|    Elenore Choy|
|  Sheryll Towler|
|  Margene Moores|
|     Neda Briski|
|    Claude Panos|
|  Celeste Lollis|
|  Cordie Harnois|
|       Kena Wild|
| Ernest Rossbach|
|  Latia Vanhoose|
|  Latia Vanhoose|
|     Neda Briski|
|  Latia Vanhoose|
|  Loris Crossett|
|  Annika Hoffman|
|   Santa Kerfien|
|Mickey Cortright|
+----------------+
only showing top 20 rows

# Filter

In [98]:
df.filter(df.name.like('%nh%')).show()

+---+------+--------------+------+-------+-----+--------------------+
|Age|gender|          name|course|   roll|marks|               email|
+---+------+--------------+------+-------+-----+--------------------+
| 28|Female|Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|
| 29|Female|Latia Vanhoose|   MVC| 132110|   55|Eda Neathery_Nico...|
| 29|Female|Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|
| 29|  Male|Latia Vanhoose| Cloud|1832268|   60|Marylee Capasso_S...|
| 29|  Male|Latia Vanhoose|   OOP|2372748|   94|Latia Vanhoose_La...|
| 29|Female|Latia Vanhoose|    PF|2861854|   42|Claude Panos_Nico...|
| 29|  Male|Latia Vanhoose|   MVC|2992281|   90|Elenore Choy_Cord...|
| 29|Female|Latia Vanhoose|   MVC|3091650|   30|Cordie Harnois_Se...|
| 29|Female|Latia Vanhoose|   OOP|3841395|   26|Kizzy Brenner_Eda...|
| 29|  Male|Latia Vanhoose| Cloud|4661276|   40|Jc Andrepont_Anni...|
| 28|Female|Latia Vanhoose|   OOP|4792828|   72|Tamera Blakley_Mi...|
| 28|Female|Latia Vanhoose|    PF|5222171|   73|Toshiko Hillyard_...|
| 28|Female|Latia Vanhoose| Cloud|6701628|   33|Abram Nagao_Cheri...|
| 29|Female|Latia Vanhoose|   MVC|6771882|   49|Alberta Freund_La...|
| 28|Female|Latia Vanhoose|   MVC|7381991|   94|Eda Neathery_Mich...|
| 29|  Male|Latia Vanhoose| Cloud|7721956|   45|Jalisa Swenson_An...|
| 28|  Male|Latia Vanhoose|   OOP|7741757|   66|Loris Crossett_Na...|
| 28|  Male|Latia Vanhoose|   DSA|7792270|   37|Eda Neathery_Donn...|
| 28|  Male|Latia Vanhoose|   DSA|9442974|   29|Jc Andrepont_Cele...|
| 28|Female|Latia Vanhoose| Cloud|9471888|   56|Naoma Fritts_Kena...|
+---+------+--------------+------+-------+-----+--------------------+

In [99]:
df.filter(df.course=='DB').show()

+---+------+-----------------+------+-------+-----+--------------------+
|Age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|Female|  Hubert Oliveras|    DB|  02984|   59|Annika Hoffman_Na...|
| 29|Female|     Elenore Choy|    DB|  32877|   29|Billi Clore_Mitzi...|
| 29|  Male|  Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|
| 28|Female|   Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|
| 29|Female|   Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|
| 28|Female| Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|
| 28|Female|      Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|
| 28|  Male|    Kizzy Brenner|    DB| 381712|   36|Paris Hutton_Kena...|
| 28|  Male| Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|
| 29|  Male|     Paris Hutton|    DB| 481229|   57|Clementina Menke_...|
| 28|Female| Mickey Cortright|    DB| 551389|   43|Tijuana Kropf_Jen...|
| 28|Female|Leontine Phillips|    DB| 602404|   48|Neda Briski_Cheri...|
| 28|Female|  Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|
| 29|Female|     Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|
| 29|  Male| Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|
| 29|Female|  Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|
| 29|  Male|     Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|
| 28|  Male|   Annika Hoffman|    DB|1031544|   44|Dustin Feagins_So...|
| 28|  Male|   Nicole Harwood|    DB|1211495|   28|Melani Engberg_Jc...|
| 29|Female|     Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [110]:
# creating column with all values 120
from pyspark.sql.functions import col,lit 
df1=df.withColumn("Total",lit(120))

In [114]:
df_avg = df1.withColumn('average',col('marks')/col('Total')*100)
df_avg.show()

+---+------+----------------+------+------+-----+--------------------+-----+------------------+
|Age|gender|            name|course|  roll|marks|               email|Total|           average|
+---+------+----------------+------+------+-----+--------------------+-----+------------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|  120|49.166666666666664|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|  120| 51.66666666666667|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|  120|              37.5|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|  120|24.166666666666668|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|  120|34.166666666666664|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|  120|26.666666666666668|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|  120| 57.49999999999999|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|  120| 70.83333333333334|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|  120|53.333333333333336|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|  120|              42.5|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|  120|29.166666666666668|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|  120|44.166666666666664|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|  120|              22.5|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|  120| 45.83333333333333|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|  120|              35.0|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|  120|              22.5|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|  120|              30.0|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|  120|18.333333333333332|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|  120|46.666666666666664|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|  120| 51.66666666666667|
+---+------+----------------+------+------+-----+--------------------+-----+------------------+
only showing top 20 rows

In [122]:
oop_80=df_avg.filter(( df_avg.average>80.0) & (df_avg.course=='OOP'))

In [124]:
cloud_60 =df_avg.filter(( df_avg.average>60.0) & (df_avg.course=='Cloud'))

In [125]:
df.select('name','marks').show()

+----------------+-----+
|            name|marks|
+----------------+-----+
| Hubert Oliveras|   59|
|Toshiko Hillyard|   62|
|  Celeste Lollis|   45|
|    Elenore Choy|   29|
|  Sheryll Towler|   41|
|  Margene Moores|   32|
|     Neda Briski|   69|
|    Claude Panos|   85|
|  Celeste Lollis|   64|
|  Cordie Harnois|   51|
|       Kena Wild|   35|
| Ernest Rossbach|   53|
|  Latia Vanhoose|   27|
|  Latia Vanhoose|   55|
|     Neda Briski|   42|
|  Latia Vanhoose|   27|
|  Loris Crossett|   36|
|  Annika Hoffman|   22|
|   Santa Kerfien|   56|
|Mickey Cortright|   62|
+----------------+-----+
only showing top 20 rows

# distinct, count

In [130]:
df.select('Age','gender','course').distinct().show()

+---+------+------+
|Age|gender|course|
+---+------+------+
| 28|  Male| Cloud|
| 28|Female|    DB|
| 28|Female|   MVC|
| 29|  Male|    PF|
| 28|Female|   OOP|
| 29|Female| Cloud|
| 29|  Male| Cloud|
| 29|Female|   DSA|
| 29|  Male|   OOP|
| 29|  Male|    DB|
| 28|Female|    PF|
| 29|Female|   MVC|
| 29|Female|    DB|
| 28|  Male|    PF|
| 29|  Male|   DSA|
| 28|Female| Cloud|
| 29|Female|   OOP|
| 29|  Male|   MVC|
| 28|  Male|   OOP|
| 28|  Male|   DSA|
+---+------+------+
only showing top 20 rows

In [134]:
employee = spark.read.options(inferschema=True).csv('data/OfficeData.csv',header=True)

In [136]:
employee.printSchema()

root
 |-- employee_name: string (nullable = true)
 |-- department: string (nullable = true)
 |-- state: string (nullable = true)
 |-- salary: integer (nullable = true)
 |-- age: integer (nullable = true)
 |-- bonus: integer (nullable = true)

## drop duplicated

In [ ]:
# df.dropDuplicates('gender').show() # if there is female then others female is removed

# Sort and orderBy

In [139]:
employee.sort(col('bonus').asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
+-------------+----------+-----+------+---+-----+

In [140]:
employee.sort(col('age').desc(),col('salary').asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [147]:
employee.orderBy(col('Age').desc(),col('salary').asc(),col('bonus').desc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

# Groupby

In [158]:

df.groupBy('course').sum('marks').show()
df.groupBy('course').count().show()
df.groupBy('gender').avg('marks').show()

+------+----------+
|course|sum(marks)|
+------+----------+
|    PF|      9933|
|    DB|      9270|
|   MVC|      9585|
|   DSA|     10950|
| Cloud|     11443|
|   OOP|      8916|
+------+----------+

+------+-----+
|course|count|
+------+-----+
|    PF|  166|
|    DB|  157|
|   MVC|  157|
|   DSA|  176|
| Cloud|  192|
|   OOP|  152|
+------+-----+

+------+------------------+
|gender|        avg(marks)|
+------+------------------+
|Female|59.153692614770456|
|  Male| 61.04408817635271|
+------+------------------+

In [162]:
df.groupBy('gender').max('marks').show()
df.groupBy('gender').min('marks').show()
df.groupBy('course').min('marks').show()

+------+----------+
|gender|max(marks)|
+------+----------+
|Female|        99|
|  Male|        99|
+------+----------+

+------+----------+
|gender|min(marks)|
+------+----------+
|Female|        20|
|  Male|        20|
+------+----------+

+------+----------+
|course|min(marks)|
+------+----------+
|    PF|        20|
|    DB|        20|
|   MVC|        22|
|   DSA|        20|
| Cloud|        20|
|   OOP|        20|
+------+----------+

+------+----------+
|course|max(marks)|
+------+----------+
|    PF|        99|
|    DB|        98|
|   MVC|        99|
|   DSA|        99|
| Cloud|        99|
|   OOP|        99|
+------+----------+

In [163]:
df.groupBy('course').max('marks').show()

+------+----------+
|course|max(marks)|
+------+----------+
|    PF|        99|
|    DB|        98|
|   MVC|        99|
|   DSA|        99|
| Cloud|        99|
|   OOP|        99|
+------+----------+

In [18]:
from pyspark.sql.functions import  min,max,sum,avg,count,col,lit 
df.groupBy('course','gender').agg(count("*").alias('total ernolments'),sum('marks').alias('total'),min('marks').alias('min_marks')\
    ,max('marks').alias('Max_marks'),avg('marks').alias('average')).show()

+------+------+----------------+-----+---------+---------+------------------+
|course|gender|total ernolments|total|min_marks|Max_marks|           average|
+------+------+----------------+-----+---------+---------+------------------+
|   OOP|  Male|              70| 4234|       20|       99| 60.48571428571429|
|    DB|  Male|              82| 5073|       20|       98| 61.86585365853659|
| Cloud|Female|             106| 6316|       20|       99| 59.58490566037736|
|   MVC|  Male|              86| 5241|       22|       99| 60.94186046511628|
|   DSA|Female|              98| 6124|       20|       99| 62.48979591836735|
|    PF|  Male|              97| 5960|       20|       99| 61.44329896907217|
|   MVC|Female|              71| 4344|       22|       99|61.183098591549296|
| Cloud|  Male|              86| 5127|       21|       97|59.616279069767444|
|    PF|Female|              69| 3973|       20|       99| 57.57971014492754|
|   DSA|  Male|              78| 4826|       20|       99| 61.87179487179487|
|    DB|Female|              75| 4197|       20|       96|             55.96|
|   OOP|Female|              82| 4682|       21|       99| 57.09756097560975|
+------+------+----------------+-----+---------+---------+------------------+

In [167]:
employee.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

In [168]:
employee.groupBy('department').agg(count("*"),sum('salary'),min('salary').alias('MIN_SAL'),max('salary').alias('MaxSal')\
    ,sum('bonus').alias('total_bonus'),avg('age').alias('average_age')).show()

+----------+--------+-----------+-------+------+-----------+-----------+
|department|count(1)|sum(salary)|MIN_SAL|MaxSal|total_bonus|average_age|
+----------+--------+-----------+-------+------+-----------+-----------+
|     Sales|       3|     257000|  81000| 90000|      53000|       40.0|
|   Finance|       4|     351000|  79000| 99000|      81000|      38.25|
| Marketing|       2|     171000|  80000| 91000|      39000|       37.5|
+----------+--------+-----------+-------+------+-----------+-----------+

In [11]:
df_male = df.filter(df.gender=='Male')
df_total = df_male.groupBy('course','gender').agg(count('*').alias('Total_erno'))

In [15]:
df_total.where(df_total.Total_erno>85).show()

+------+------+----------+
|course|gender|Total_erno|
+------+------+----------+
|   MVC|  Male|        86|
|    PF|  Male|        97|
| Cloud|  Male|        86|
+------+------+----------+

In [20]:
df.filter(df.gender=='Male').groupBy('course','gender').agg(count('*').alias('Total_en')).filter(col('Total_en')>85).show()

+------+------+--------+
|course|gender|Total_en|
+------+------+--------+
|   MVC|  Male|      86|
|    PF|  Male|      97|
| Cloud|  Male|      86|
+------+------+--------+

In [24]:

df.groupBy('gender','course').sum('marks').orderBy(col('course'),col('gender').desc()).show()

+------+------+----------+
|gender|course|sum(marks)|
+------+------+----------+
|  Male| Cloud|      5127|
|Female| Cloud|      6316|
|  Male|    DB|      5073|
|Female|    DB|      4197|
|  Male|   DSA|      4826|
|Female|   DSA|      6124|
|  Male|   MVC|      5241|
|Female|   MVC|      4344|
|  Male|   OOP|      4234|
|Female|   OOP|      4682|
|  Male|    PF|      5960|
|Female|    PF|      3973|
+------+------+----------+

In [25]:

df.groupBy('course','gender').sum('marks').orderBy(col('course'),col('gender').desc()).show()

+------+------+----------+
|course|gender|sum(marks)|
+------+------+----------+
| Cloud|  Male|      5127|
| Cloud|Female|      6316|
|    DB|  Male|      5073|
|    DB|Female|      4197|
|   DSA|  Male|      4826|
|   DSA|Female|      6124|
|   MVC|  Male|      5241|
|   MVC|Female|      4344|
|   OOP|  Male|      4234|
|   OOP|Female|      4682|
|    PF|  Male|      5960|
|    PF|Female|      3973|
+------+------+----------+

In [27]:
df.groupBy('course','Age').agg(min('marks').alias('min_marks'),max('marks').alias('Max_mark'),avg('marks').alias('average')).show()

+------+---+---------+--------+------------------+
|course|Age|min_marks|Max_mark|           average|
+------+---+---------+--------+------------------+
|   MVC| 28|       23|      99| 60.44444444444444|
|   MVC| 29|       22|      99| 61.56470588235294|
| Cloud| 28|       20|      99|             58.08|
|    PF| 29|       20|      99|56.275862068965516|
|    PF| 28|       20|      98| 63.75949367088607|
|   OOP| 29|       20|      99|59.729729729729726|
|   DSA| 28|       20|      99|  64.6867469879518|
| Cloud| 29|       21|      98|             61.25|
|    DB| 28|       21|      98| 58.76829268292683|
|   DSA| 29|       20|      99| 60.01075268817204|
|   OOP| 28|       23|      99| 57.64102564102564|
|    DB| 29|       20|      98|59.346666666666664|
+------+---+---------+--------+------------------+

In [28]:
df_word = spark.read.text('data/WordData.txt')

In [32]:
df_word.groupBy('value').count().show()

+------+-----+
| value|count|
+------+-----+
|   Mic|   10|
| Chair|   15|
|  Book|    5|
|Laptop|    5|
|   Bag|    5|
|Mobile|    5|
| Apple|   10|
+------+-----+

In [33]:
from pyspark.sql.functions import udf,lit,col 
from pyspark.sql.types import IntegerType

def total_sal(salary,bonus):
    return salary+bonus 

total_salary = udf(lambda x,y: total_sal(x,y),IntegerType())

In [34]:
employee = spark.read.options(inferschema=True).csv('data/OfficeData.csv',header=True)

In [35]:
employee.withColumn('Total_sal',total_salary(employee.salary,employee.bonus)).show()

+-------------+----------+-----+------+---+-----+---------+
|employee_name|department|state|salary|age|bonus|Total_sal|
+-------------+----------+-----+------+---+-----+---------+
|        James|     Sales|   NY| 90000| 34|10000|   100000|
|      Michael|     Sales|   NY| 86000| 56|20000|   106000|
|       Robert|     Sales|   CA| 81000| 30|23000|   104000|
|        Maria|   Finance|   CA| 90000| 24|23000|   113000|
|        Raman|   Finance|   CA| 99000| 40|24000|   123000|
|        Scott|   Finance|   NY| 83000| 36|19000|   102000|
|          Jen|   Finance|   NY| 79000| 53|15000|    94000|
|         Jeff| Marketing|   CA| 80000| 25|18000|    98000|
|        Kumar| Marketing|   NY| 91000| 50|21000|   112000|
+-------------+----------+-----+------+---+-----+---------+

In [36]:
employee.withColumn('Total_sal',total_sal(employee.salary,employee.bonus)).show()

+-------------+----------+-----+------+---+-----+---------+
|employee_name|department|state|salary|age|bonus|Total_sal|
+-------------+----------+-----+------+---+-----+---------+
|        James|     Sales|   NY| 90000| 34|10000|   100000|
|      Michael|     Sales|   NY| 86000| 56|20000|   106000|
|       Robert|     Sales|   CA| 81000| 30|23000|   104000|
|        Maria|   Finance|   CA| 90000| 24|23000|   113000|
|        Raman|   Finance|   CA| 99000| 40|24000|   123000|
|        Scott|   Finance|   NY| 83000| 36|19000|   102000|
|          Jen|   Finance|   NY| 79000| 53|15000|    94000|
|         Jeff| Marketing|   CA| 80000| 25|18000|    98000|
|        Kumar| Marketing|   NY| 91000| 50|21000|   112000|
+-------------+----------+-----+------+---+-----+---------+

In [65]:
def increment(state:str,salary:int,bonus:int):
    if state=="NY":
        salary = salary/10 
        bonus = 0.05*bonus 
    if state=="CA":
        salary = 0.12*salary
        bonus = 0.03*bonus 
    return int(salary+bonus )

incre_sal = udf(increment,IntegerType())

In [66]:
employee.withColumn('increment',incre_sal(col('state'),col('salary'),col('bonus'))).show()

+-------------+----------+-----+------+---+-----+---------+
|employee_name|department|state|salary|age|bonus|increment|
+-------------+----------+-----+------+---+-----+---------+
|        James|     Sales|   NY| 90000| 34|10000|     9500|
|      Michael|     Sales|   NY| 86000| 56|20000|     9600|
|       Robert|     Sales|   CA| 81000| 30|23000|    10410|
|        Maria|   Finance|   CA| 90000| 24|23000|    11490|
|        Raman|   Finance|   CA| 99000| 40|24000|    12600|
|        Scott|   Finance|   NY| 83000| 36|19000|     9250|
|          Jen|   Finance|   NY| 79000| 53|15000|     8650|
|         Jeff| Marketing|   CA| 80000| 25|18000|    10140|
|        Kumar| Marketing|   NY| 91000| 50|21000|    10150|
+-------------+----------+-----+------+---+-----+---------+

In [58]:
increment('NY',90000,10000)

109500

# DtatFrame to RDD

In [67]:
rdd=df.rdd

In [68]:
rdd.collect()

[Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=2984, marks=59, email='Annika Hoffman_Naoma Fritts@OOP.com'),
 Row(age=29, gender='Female', name='Toshiko Hillyard', course='Cloud', roll=12899, marks=62, email='Margene Moores_Marylee Capasso@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=32877, marks=29, email='Billi Clore_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='Cloud', roll=72409, marks=85, email='Sheryll Towler_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Cordie Harnois', course='OOP', roll=92882, marks=51, email='Judie Chipps_Clementina Menke@MVC.com'),
 Row(age=29, gender='Female', name='Kena Wild', course='DSA', roll=102285, marks=35, email='Dustin Feagins_Margene Moores@OOP.com'),
 Row(age=29, gender='Male', name='Ernest Rossbach', course='DB', roll=111449, marks=53, email='Maybell Duguay_Abram Nagao@OOP.com'),
 Row(age=28, gender='Female', name='Latia Vanhoose', course='DB', roll=122502, marks=27, email='Latia Vanhoose_Mitzi Seldon@OOP.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='MVC', roll=132110, marks=55, email='Eda Neathery_Nicole Harwood@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=141770, marks=42, email='Margene Moores_Michelle Ruggiero@MVC.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='DB', roll=152159, marks=27, email='Claude Panos_Santa Kerfien@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='MVC', roll=161771, marks=36, email='Mitzi Seldon_Jenna Montague@MVC.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=171660, marks=22, email='Taryn Brownlee_Mitzi Seldon@MVC.com'),
 Row(age=29, gender='Male', name='Santa Kerfien', course='PF', roll=182129, marks=56, email='Judie Chipps_Taryn Brownlee@Cloud.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=192537, marks=62, email='Ernest Rossbach_Marylee Capasso@Cloud.com'),
 Row(age=29, gender='Female', name='Loris Crossett', course='PF', roll=201487, marks=96, email='Elenore Choy_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='PF', roll=211508, marks=23, email='Cordie Harnois_Judie Chipps@PF.com'),
 Row(age=28, gender='Female', name='Kena Wild', course='Cloud', roll=221750, marks=60, email='Mitzi Seldon_Jenna Montague@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='DSA', roll=232060, marks=58, email='Billi Clore_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='Cloud', roll=242254, marks=68, email='Jc Andrepont_Hubert Oliveras@Cloud.com'),
 Row(age=28, gender='Female', name='Alberta Freund', course='OOP', roll=251805, marks=83, email='Annika Hoffman_Sheryll Towler@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='Cloud', roll=261439, marks=20, email='Nicole Harwood_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=271472, marks=99, email='Sheryll Towler_Alberta Freund@DSA.com'),
 Row(age=29, gender='Female', name='Cheri Kenney', course='Cloud', roll=281408, marks=43, email='Annika Hoffman_Melani Engberg@Cloud.com'),
 Row(age=28, gender='Female', name='Dustin Feagins', course='DSA', roll=291984, marks=82, email='Abram Nagao_Kena Wild@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='Cloud', roll=302130, marks=59, email='Sheryll Towler_Leontine Phillips@PF.com'),
 Row(age=28, gender='Female', name='Anna Santos', course='DB', roll=311589, marks=79, email='Celeste Lollis_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Cheri Kenney', course='MVC', roll=321816, marks=24, email='Kena Wild_Michelle Ruggiero@DB.com'),
 Row(age=28, gender='Female', name='Loris Crossett', course='PF', roll=332739, marks=62, email='Michelle Ruggiero_Clementina Menke@DB.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DSA', roll=342003, marks=44, email='Mitzi Seldon_Jeannetta Golden@PF.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=372873, marks=45, email='Ernest Rossbach_Toshiko Hillyard@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Female', name='Kizzy Brenner', course='Cloud', roll=402409, marks=27, email='Ernest Rossbach_Gonzalo Ferebee@OOP.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='DSA', roll=411479, marks=42, email='Kena Wild_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Female', name='Jalisa Swenson', course='OOP', roll=431352, marks=25, email='Gonzalo Ferebee_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Somer Stoecker', course='Cloud', roll=442028, marks=34, email='Taryn Brownlee_Taryn Brownlee@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='DSA', roll=452141, marks=29, email='Leontine Phillips_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=472550, marks=35, email='Mitzi Seldon_Abram Nagao@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='DB', roll=481229, marks=57, email='Clementina Menke_Paris Hutton@MVC.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=492159, marks=60, email='Nicole Harwood_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Female', name='Jenna Montague', course='MVC', roll=502585, marks=43, email='Hubert Oliveras_Jc Andrepont@DSA.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='Cloud', roll=512047, marks=76, email='Taryn Brownlee_Judie Chipps@DSA.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='OOP', roll=521221, marks=77, email='Hubert Oliveras_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='OOP', roll=542821, marks=28, email='Hubert Oliveras_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=551389, marks=43, email='Tijuana Kropf_Jenna Montague@DB.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='DSA', roll=562065, marks=85, email='Jc Andrepont_Melani Engberg@OOP.com'),
 Row(age=28, gender='Female', name='Tijuana Kropf', course='PF', roll=571047, marks=41, email='Loris Crossett_Sebrina Maresca@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='DSA', roll=592061, marks=83, email='Eda Neathery_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='DB', roll=602404, marks=48, email='Neda Briski_Cheri Kenney@PF.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='Cloud', roll=612490, marks=82, email='Sebrina Maresca_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='Cloud', roll=632793, marks=75, email='Tijuana Kropf_Elenore Choy@PF.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='MVC', roll=651649, marks=92, email='Latia Vanhoose_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Hubert Oliveras', course='MVC', roll=672451, marks=28, email='Annika Hoffman_Mickey Cortright@DSA.com'),
 Row(age=29, gender='Male', name='Sheryll Towler', course='PF', roll=682533, marks=42, email='Billi Clore_Anna Santos@PF.com'),
 Row(age=28, gender='Female', name='Jenna Montague', course='DSA', roll=691564, marks=26, email='Mitzi Seldon_Sebrina Maresca@Cloud.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='PF', roll=701486, marks=99, email='Clementina Menke_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='MVC', roll=711153, marks=45, email='Marylee Capasso_Hubert Oliveras@DB.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Celeste Lollis', course='DSA', roll=731879, marks=76, email='Hubert Oliveras_Gonzalo Ferebee@DSA.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=741875, marks=57, email='Sheryll Towler_Cheri Kenney@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='MVC', roll=752504, marks=22, email='Elenore Choy_Elenore Choy@DB.com'),
 Row(age=29, gender='Female', name='Margene Moores', course='MVC', roll=761843, marks=48, email='Ernest Rossbach_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=771081, marks=79, email='Kizzy Brenner_Dustin Feagins@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=29, gender='Female', name='Billi Clore', course='OOP', roll=791519, marks=93, email='Elenore Choy_Jalisa Swenson@MVC.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='Cloud', roll=801693, marks=38, email='Niki Klimek_Kizzy Brenner@DB.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=811824, marks=55, email='Maybell Duguay_Melani Engberg@DB.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=842515, marks=68, email='Neda Briski_Hubert Oliveras@OOP.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='Cloud', roll=851620, marks=34, email='Melani Engberg_Sheryll Towler@PF.com'),
 Row(age=29, gender='Female', name='Taryn Brownlee', course='MVC', roll=861849, marks=39, email='Billi Clore_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Female', name='Sheryll Towler', course='DSA', roll=871967, marks=64, email='Michelle Ruggiero_Billi Clore@Cloud.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='DB', roll=882200, marks=76, email='Michelle Ruggiero_Jenna Montague@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='DSA', roll=901958, marks=64, email='Kizzy Brenner_Jc Andrepont@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='PF', roll=911593, marks=46, email='Gonzalo Ferebee_Mitzi Seldon@PF.com'),
 Row(age=29, gender='Female', name='Sebrina Maresca', course='DB', roll=922210, marks=54, email='Toshiko Hillyard_Santa Kerfien@MVC.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='DB', roll=931295, marks=79, email='Hubert Oliveras_Sheryll Towler@DSA.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='MVC', roll=941783, marks=94, email='Paris Hutton_Naoma Fritts@DB.com'),
 Row(age=28, gender='Female', name='Lawanda Wohlwend', course='DSA', roll=951686, marks=60, email='Loris Crossett_Nicole Harwood@DSA.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='MVC', roll=962235, marks=32, email='Jenna Montague_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='PF', roll=972733, marks=20, email='Eda Neathery_Eda Neathery@MVC.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='PF', roll=982443, marks=94, email='Santa Kerfien_Kizzy Brenner@DB.com'),
 Row(age=28, gender='Female', name='Marylee Capasso', course='OOP', roll=991770, marks=86, email='Margene Moores_Clementina Menke@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=29, gender='Female', name='Eda Neathery', course='Cloud', roll=1011971, marks=91, email='Margene Moores_Elenore Choy@MVC.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='DSA', roll=1022971, marks=99, email='Cordie Harnois_Clementina Menke@OOP.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='DSA', roll=1041483, marks=28, email='Billi Clore_Santa Kerfien@DSA.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='MVC', roll=1061068, marks=82, email='Santa Kerfien_Hubert Oliveras@MVC.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='PF', roll=1071717, marks=54, email='Celeste Lollis_Leontine Phillips@OOP.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='OOP', roll=1081294, marks=94, email='Kizzy Brenner_Anna Santos@OOP.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=1092702, marks=79, email='Marylee Capasso_Alberta Freund@OOP.com'),
 Row(age=29, gender='Female', name='Maybell Duguay', course='MVC', roll=1102536, marks=22, email='Somer Stoecker_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='PF', roll=1112161, marks=42, email='Nicole Harwood_Niki Klimek@DB.com'),
 Row(age=28, gender='Female', name='Bonita Higuera', course='DSA', roll=1122348, marks=51, email='Somer Stoecker_Jenna Montague@DB.com'),
 Row(age=29, gender='Female', name='Melani Engberg', course='OOP', roll=1132093, marks=76, email='Kena Wild_Neda Briski@Cloud.com'),
 Row(age=29, gender='Female', name='Marylee Capasso', course='OOP', roll=1142653, marks=61, email='Cordie Harnois_Alberta Freund@DSA.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=1152571, marks=62, email='Latia Vanhoose_Maybell Duguay@PF.com'),
 Row(age=29, gender='Female', name='Dustin Feagins', course='OOP', roll=1161607, marks=37, email='Eda Neathery_Marylee Capasso@MVC.com'),
 Row(age=28, gender='Female', name='Niki Klimek', course='PF', roll=1172784, marks=24, email='Jeannetta Golden_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Abram Nagao', course='DSA', roll=1181007, marks=57, email='Anna Santos_Anna Santos@DSA.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=29, gender='Female', name='Ernest Rossbach', course='MVC', roll=1201427, marks=80, email='Elenore Choy_Jenna Montague@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='DB', roll=1222887, marks=75, email='Hubert Oliveras_Somer Stoecker@Cloud.com'),
 Row(age=28, gender='Female', name='Cordie Harnois', course='OOP', roll=1231943, marks=68, email='Mickey Cortright_Kizzy Brenner@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='Cloud', roll=1261533, marks=70, email='Dustin Feagins_Nicole Harwood@PF.com'),
 Row(age=28, gender='Female', name='Eda Neathery', course='Cloud', roll=1272870, marks=69, email='Somer Stoecker_Dustin Feagins@DB.com'),
 Row(age=28, gender='Female', name='Toshiko Hillyard', course='DSA', roll=1282835, marks=79, email='Somer Stoecker_Toshiko Hillyard@OOP.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='DB', roll=1301784, marks=24, email='Celeste Lollis_Tamera Blakley@DB.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='MVC', roll=1322629, marks=87, email='Judie Chipps_Michelle Ruggiero@Cloud.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=1332072, marks=88, email='Billi Clore_Kizzy Brenner@Cloud.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Jalisa Swenson', course='DSA', roll=1362151, marks=51, email='Lawanda Wohlwend_Jenna Montague@PF.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='Cloud', roll=1392791, marks=94, email='Anna Santos_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=29, gender='Female', name='Clementina Menke', course='OOP', roll=1412376, marks=65, email='Elenore Choy_Latia Vanhoose@DSA.com'),
 Row(age=29, gender='Female', name='Mickey Cortright', course='Cloud', roll=1421542, marks=71, email='Latia Vanhoose_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Leontine Phillips', course='DB', roll=1432252, marks=67, email='Billi Clore_Sheryll Towler@DB.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='PF', roll=1441367, marks=95, email='Jc Andrepont_Anna Santos@DSA.com'),
 Row(age=28, gender='Female', name='Gonzalo Ferebee', course='DB', roll=1451513, marks=69, email='Claude Panos_Tamera Blakley@PF.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='DB', roll=1461078, marks=31, email='Tijuana Kropf_Billi Clore@OOP.com'),

In [70]:
rdd.filter(lambda x: x['age']==28).collect()

[Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=2984, marks=59, email='Annika Hoffman_Naoma Fritts@OOP.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='Cloud', roll=72409, marks=85, email='Sheryll Towler_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=28, gender='Female', name='Latia Vanhoose', course='DB', roll=122502, marks=27, email='Latia Vanhoose_Mitzi Seldon@OOP.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=192537, marks=62, email='Ernest Rossbach_Marylee Capasso@Cloud.com'),
 Row(age=28, gender='Female', name='Kena Wild', course='Cloud', roll=221750, marks=60, email='Mitzi Seldon_Jenna Montague@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='DSA', roll=232060, marks=58, email='Billi Clore_Abram Nagao@MVC.com'),
 Row(age=28, gender='Female', name='Alberta Freund', course='OOP', roll=251805, marks=83, email='Annika Hoffman_Sheryll Towler@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='Cloud', roll=261439, marks=20, email='Nicole Harwood_Judie Chipps@DB.com'),
 Row(age=28, gender='Female', name='Dustin Feagins', course='DSA', roll=291984, marks=82, email='Abram Nagao_Kena Wild@Cloud.com'),
 Row(age=28, gender='Female', name='Anna Santos', course='DB', roll=311589, marks=79, email='Celeste Lollis_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Cheri Kenney', course='MVC', roll=321816, marks=24, email='Kena Wild_Michelle Ruggiero@DB.com'),
 Row(age=28, gender='Female', name='Loris Crossett', course='PF', roll=332739, marks=62, email='Michelle Ruggiero_Clementina Menke@DB.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DSA', roll=342003, marks=44, email='Mitzi Seldon_Jeannetta Golden@PF.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Female', name='Kizzy Brenner', course='Cloud', roll=402409, marks=27, email='Ernest Rossbach_Gonzalo Ferebee@OOP.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Female', name='Jalisa Swenson', course='OOP', roll=431352, marks=25, email='Gonzalo Ferebee_Judie Chipps@DB.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='DSA', roll=452141, marks=29, email='Leontine Phillips_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=551389, marks=43, email='Tijuana Kropf_Jenna Montague@DB.com'),
 Row(age=28, gender='Female', name='Tijuana Kropf', course='PF', roll=571047, marks=41, email='Loris Crossett_Sebrina Maresca@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='DB', roll=602404, marks=48, email='Neda Briski_Cheri Kenney@PF.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='Cloud', roll=612490, marks=82, email='Sebrina Maresca_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=28, gender='Female', name='Jenna Montague', course='DSA', roll=691564, marks=26, email='Mitzi Seldon_Sebrina Maresca@Cloud.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Celeste Lollis', course='DSA', roll=731879, marks=76, email='Hubert Oliveras_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=771081, marks=79, email='Kizzy Brenner_Dustin Feagins@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='Cloud', roll=801693, marks=38, email='Niki Klimek_Kizzy Brenner@DB.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='Cloud', roll=851620, marks=34, email='Melani Engberg_Sheryll Towler@PF.com'),
 Row(age=28, gender='Female', name='Sheryll Towler', course='DSA', roll=871967, marks=64, email='Michelle Ruggiero_Billi Clore@Cloud.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='DSA', roll=901958, marks=64, email='Kizzy Brenner_Jc Andrepont@DB.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='MVC', roll=941783, marks=94, email='Paris Hutton_Naoma Fritts@DB.com'),
 Row(age=28, gender='Female', name='Lawanda Wohlwend', course='DSA', roll=951686, marks=60, email='Loris Crossett_Nicole Harwood@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='PF', roll=972733, marks=20, email='Eda Neathery_Eda Neathery@MVC.com'),
 Row(age=28, gender='Female', name='Marylee Capasso', course='OOP', roll=991770, marks=86, email='Margene Moores_Clementina Menke@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='MVC', roll=1061068, marks=82, email='Santa Kerfien_Hubert Oliveras@MVC.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='OOP', roll=1081294, marks=94, email='Kizzy Brenner_Anna Santos@OOP.com'),
 Row(age=28, gender='Female', name='Bonita Higuera', course='DSA', roll=1122348, marks=51, email='Somer Stoecker_Jenna Montague@DB.com'),
 Row(age=28, gender='Female', name='Niki Klimek', course='PF', roll=1172784, marks=24, email='Jeannetta Golden_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=28, gender='Female', name='Cordie Harnois', course='OOP', roll=1231943, marks=68, email='Mickey Cortright_Kizzy Brenner@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=28, gender='Female', name='Eda Neathery', course='Cloud', roll=1272870, marks=69, email='Somer Stoecker_Dustin Feagins@DB.com'),
 Row(age=28, gender='Female', name='Toshiko Hillyard', course='DSA', roll=1282835, marks=79, email='Somer Stoecker_Toshiko Hillyard@OOP.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='MVC', roll=1322629, marks=87, email='Judie Chipps_Michelle Ruggiero@Cloud.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='PF', roll=1441367, marks=95, email='Jc Andrepont_Anna Santos@DSA.com'),
 Row(age=28, gender='Female', name='Gonzalo Ferebee', course='DB', roll=1451513, marks=69, email='Claude Panos_Tamera Blakley@PF.com'),
 Row(age=28, gender='Male', name='Jc Andrepont', course='DSA', roll=1492828, marks=78, email='Celeste Lollis_Kizzy Brenner@MVC.com'),
 Row(age=28, gender='Female', name='Cordie Harnois', course='MVC', roll=1501333, marks=94, email='Gonzalo Ferebee_Tijuana Kropf@OOP.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='PF', roll=1521724, marks=91, email='Eda Neathery_Jeannetta Golden@MVC.com'),
 Row(age=28, gender='Female', name='Marylee Capasso', course='Cloud', roll=1541030, marks=58, email='Cordie Harnois_Celeste Lollis@PF.com'),
 Row(age=28, gender='Female', name='Jeannetta Golden', course='OOP', roll=1562758, marks=40, email='Jeannetta Golden_Billi Clore@Cloud.com'),
 Row(age=28, gender='Female', name='Tamera Blakley', course='PF', roll=1591554, marks=78, email='Sebrina Maresca_Tijuana Kropf@OOP.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1602777, marks=53, email='Sheryll Towler_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DB', roll=1611411, marks=96, email='Annika Hoffman_Loris Crossett@PF.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=1621905, marks=24, email='Elenore Choy_Santa Kerfien@DB.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='DSA', roll=1632185, marks=93, email='Clementina Menke_Toshiko Hillyard@Cloud.com'),
 Row(age=28, gender='Female', name='Neda Briski', course='Cloud', roll=1651303, marks=74, email='Ernest Rossbach_Donna Yerby@OOP.com'),
 Row(age=28, gender='Female', name='Loris Crossett', course='DSA', roll=1662549, marks=86, email='Paris Hutton_Latia Vanhoose@Cloud.com'),
 Row(age=28, gender='Female', name='Sebrina Maresca', course='MVC', roll=1681804, marks=27, email='Celeste Lollis_Ernest Rossbach@MVC.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='DB', roll=1692106, marks=36, email='Neda Briski_Abram Nagao@MVC.com'),
 Row(age=28, gender='Female', name='Margene Moores', course='DSA', roll=1712967, marks=41, email='Tijuana Kropf_Sheryll Towler@DB.com'),
 Row(age=28, gender='Female', name='Priscila Tavernier', course='DB', roll=1722388, marks=86, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=28, gender='Female', name='Anna Santos', course='DSA', roll=1741879, marks=89, email='Nicole Harwood_Lawanda Wohlwend@DB.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='Cloud', roll=1802934, marks=24, email='Maybell Duguay_Paris Hutton@PF.com'),
 Row(age=28, gender='Female', name='Lawanda Wohlwend', course='DB', roll=1852072, marks=30, email='Bonita Higuera_Jenna Montague@DB.com'),
 Row(age=28, gender='Female', name='Melani Engberg', course='Cloud', roll=1872667, marks=99, email='Alberta Freund_Nicole Harwood@DB.com'),
 Row(age=28, gender='Male', name='Somer Stoecker', course='Cloud', roll=1891261, marks=30, email='Taryn Brownlee_Sheryll Towler@PF.com'),
 Row(age=28, gender='Male', name='Ernest Rossbach', course='DB', roll=1901492, marks=54, email='Latia Vanhoose_Jc Andrepont@MVC.com'),
 Row(age=28, gender='Female', name='Anna Santos', course='PF', roll=1911870, marks=92, email='Sebrina Maresca_Clementina Menke@OOP.com'),
 Row(age=28, gender='Female', name='Melani Engberg', course='PF', roll=1922525, marks=83, email='Marylee Capasso_Celeste Lollis@PF.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='MVC', roll=1992202, marks=23, email='Annika Hoffman_Tamera Blakley@OOP.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2022282, marks=77, email='Anna Santos_Claude Panos@Cloud.com'),
 Row(age=28, gender='Male', name='Kena Wild', course='DB', roll=2031530, marks=93, email='Jc Andrepont_Jc Andrepont@PF.com'),
 Row(age=28, gender='Female', name='Paris Hutton', course='Cloud', roll=2051881, marks=79, email='Melani Engberg_Marylee Capasso@PF.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='OOP', roll=2061187, marks=58, email='Cheri Kenney_Cordie Harnois@PF.com'),
 Row(age=28, gender='Female', name='Eda Neathery', course='Cloud', roll=2071302, marks=95, email='Latia Vanhoose_Donna Yerby@Cloud.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DSA', roll=2081560, marks=20, email='Sheryll Towler_Donna Yerby@Cloud.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='Cloud', roll=2092176, marks=81, email='Celeste Lollis_Maybell Duguay@PF.com'),
 Row(age=28, gender='Female', name='Tijuana Kropf', course='Cloud', roll=2121632, marks=78, email='Michelle Ruggiero_Anna Santos@OOP.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='PF', roll=2162776, marks=54, email='Jenna Montague_Niki Klimek@MVC.com'),
 Row(age=28, gender='Male', name='Jeannetta Golden', course='DB', roll=2171387, marks=76, email='Cheri Kenney_Billi Clore@DB.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='DB', roll=2181375, marks=58, email='Latia Vanhoose_Eda Neathery@DSA.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='DSA', roll=2222704, marks=91, email='Judie Chipps_Jalisa Swenson@Cloud.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='OOP', roll=2232863, marks=60, email='Bonita Higuera_Lawanda Wohlwend@MVC.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='MVC', roll=2251960, marks=96, email='Somer Stoecker_Melani Engberg@DSA.com'),
 Row(age=28, gender='Female', name='Cheri Kenney', course='Cloud', roll=2281771, marks=22, email='Tamera Blakley_Abram Nagao@OOP.com'),
 Row(age=28, gender='Female', name='Marylee Capasso', course='Cloud', roll=2291595, marks=36, email='Ernest Rossbach_Mickey Cortright@MVC.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=2322537, marks=56, email='Jenna Montague_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Female', name='Taryn Brownlee', course='DSA', roll=2392929, marks=91, email='Sebrina Maresca_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Female', name='Jenna Montague', course='Cloud', roll=2402240, marks=96, email='Annika Hoffman_Dustin Feagins@Cloud.com'),
 Row(age=28, gender='Male', name='Melani Engberg', course='MVC', roll=2412019, marks=54, email='Latia Vanhoose_Melani Engberg@DSA.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='Cloud', roll=2431828, marks=26, email='Margene Moores_Somer Stoecker@PF.com'),
 Row(age=28, gender='Female', name='Jenna Montague', course='MVC', roll=2441637, marks=72, email='Cordie Harnois_Alberta Freund@OOP.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='Cloud', roll=2452108, marks=41, email='Billi Clore_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Judie Chipps', course='DB', roll=2461986, marks=53, email='Niki Klimek_Judie Chipps@MVC.com'),
 Row(age=28, gender='Female', name='Bonita Higuera', course='DSA', roll=2501639, marks=66, email='Paris Hutton_Naoma Fritts@PF.com'),
 Row(age=28, gender='Female', name='Jeannetta Golden', course='DB', roll=2522775, marks=83, email='Kizzy Brenner_Bonita Higuera@DB.com'),
 Row(age=28, gender='Female', name='Kizzy Brenner', course='OOP', roll=2542257, marks=96, email='Eda Neathery_Lawanda Wohlwend@Cloud.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='Cloud', roll=2552194, marks=42, email='Jeannetta Golden_Abram Nagao@PF.com'),
 Row(age=28, gender='Male', name='Claude Panos', course='OOP', roll=2562357, marks=50, email='Naoma Fritts_Anna Santos@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='MVC', roll=2572197, marks=43, email='Marylee Capasso_Jc Andrepont@DB.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='OOP', roll=2592369, marks=60, email='Taryn Brownlee_Sheryll Towler@OOP.com'),
 Row(age=28, gender='Female', name='Ernest Rossbach', course='Cloud', roll=2602027, marks=83, email='Alberta Freund_Gonzalo Ferebee@MVC.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=2612360, marks=27, email='Celeste Lollis_Paris Hutton@OOP.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DB', roll=2622118, marks=55, email='Mickey Cortright_Mitzi Seldon@MVC.com'),
 Row(age=28, gender='Female', name='Abram Nagao', course='DB', roll=2632057, marks=25, email='Margene Moores_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2642909, marks=58, email='Loris Crossett_Sebrina Maresca@OOP.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='Cloud', roll=2652463, marks=21, email='Eda Neathery_Annika Hoffman@Cloud.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='Cloud', roll=2682466, marks=36, email='Priscila Tavernier_Mitzi Seldon@PF.com'),
 Row(age=28, gender='Female', name='Loris Crossett', course='OOP', roll=2691881, marks=29, email='Maybell Duguay_Niki Klimek@OOP.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='PF', roll=2701239, marks=76, email='Alberta Freund_Cordie Harnois@Cloud.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='DB', roll=2732421, marks=79, email='Claude Panos_Alberta Freund@DB.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='MVC', roll=2741290, marks=32, email='Abram Nagao_Elenore Choy@MVC.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='DSA', roll=2772189, marks=98, email='Donna Yerby_Judie Chipps@PF.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='PF', roll=2792977, marks=71, email='Jalisa Swenson_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Female', name='Abram Nagao', course='Cloud', roll=2811189, marks=54, email='Kena Wild_Donna Yerby@DSA.com'),

# spark sql

In [71]:
df.createOrReplaceTempView('Student')

In [73]:
spark.sql('select * from Student where marks>60').show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
| 29|Female|  Loris Crossett|    PF|201487|   96|Elenore Choy_Lati...|
| 29|Female|     Anna Santos| Cloud|242254|   68|Jc Andrepont_Hube...|
| 28|Female|  Alberta Freund|   OOP|251805|   83|Annika Hoffman_Sh...|
| 29|Female|    Paris Hutton|   DSA|271472|   99|Sheryll Towler_Al...|
| 28|Female|  Dustin Feagins|   DSA|291984|   82|Abram Nagao_Kena ...|
| 28|Female|     Anna Santos|    DB|311589|   79|Celeste Lollis_Mi...|
| 28|Female|  Loris Crossett|    PF|332739|   62|Michelle Ruggiero...|
| 28|  Male| Hubert Oliveras|   OOP|351719|   63|Lawanda Wohlwend_...|
| 28|  Male| Sebrina Maresca|    PF|361316|   62|Nicole Harwood_La...|
| 28|  Male|    Elenore Choy|    PF|422704|   66|Marylee Capasso_N...|
| 29|  Male|     Billi Clore| Cloud|512047|   76|Taryn Brownlee_Ju...|
| 29|  Male|Toshiko Hillyard|   OOP|521221|   77|Hubert Oliveras_L...|
| 29|  Male|  Celeste Lollis|   DSA|562065|   85|Jc Andrepont_Mela...|
| 29|  Male|  Maybell Duguay|   DSA|592061|   83|Eda Neathery_Jenn...|
| 28|Female|  Somer Stoecker| Cloud|612490|   82|Sebrina Maresca_G...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [74]:
df.write.options(header=True).csv('output')

In [75]:
df_read = spark.read.options(header=True).csv('output')

In [77]:
df_read.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

# mini project

In [115]:
emp = spark.read.options(inferschema=True,header=True).csv('data/OfficeDataProject.csv')
emp.show()

+-----------+-------------------+----------+-----+------+---+-----+
|employee_id|      employee_name|department|state|salary|age|bonus|
+-----------+-------------------+----------+-----+------+---+-----+
|       1000|          Nitz Leif| Marketing|   CA|  6131| 26|  543|
|       1001|    Melissia Dedman|   Finance|   AK|  4027| 43| 1290|
|       1002|  Rudolph Barringer|        HR|   LA|  3122| 43| 1445|
|       1003|        Tamra Amber|  Accounts|   AK|  5717| 47| 1291|
|       1004|        Mullan Nitz|Purchasing|   CA|  5685| 34| 1394|
|       1005|      Zollner Karie|  Accounts|   CA|  2843| 27| 1078|
|       1006|Kaczorowski Zollner|     Sales|   CA|  7201| 21| 1834|
|       1007|      Nakano Locust| Marketing|   LA|  3444| 23| 1823|
|       1008|  Recalde Kensinger|  Accounts|   LA|  3704| 48| 1330|
|       1009|        Imai Hallie|  Accounts|   AK|  5061| 38| 1557|
|       1010|    Debroah Gallman|  Accounts|   NY|  9308| 35|  817|
|       1011|   Barringer Escoto|Purchasing|   WA|  1685| 49| 1706|
|       1012|      Soules Coogan|  Accounts|   AK|  8330| 43| 1914|
|       1013|      Luisa Suzanne|  Accounts|   CA|  1151| 37| 1095|
|       1014|      Marvis Cobian|Purchasing|   NY|  5061| 41| 1765|
|       1015|   Cobian Kensinger|     Sales|   LA|  1983| 21|  632|
|       1016|      Gilma Margret| Marketing|   CA|  2919| 45| 1762|
|       1017| Ellingsworth Ilana|  Accounts|   WA|  9614| 26| 1964|
|       1018| Vankirk Jacquelyne|Purchasing|   NY|  8636| 47| 1192|
|       1019|    Zollner Juliana|        HR|   NY|  9739| 30| 1119|
+-----------+-------------------+----------+-----+------+---+-----+
only showing top 20 rows

In [116]:
emp.count()

1000

In [117]:
emp.select('department').distinct().count()

6

In [118]:
emp.select('department').distinct().show()

+----------+
|department|
+----------+
|     Sales|
|        HR|
|   Finance|
|Purchasing|
| Marketing|
|  Accounts|
+----------+

In [119]:
emp.groupBy('department').count().show()

+----------+-----+
|department|count|
+----------+-----+
|     Sales|  169|
|        HR|  171|
|   Finance|  162|
|Purchasing|  166|
| Marketing|  170|
|  Accounts|  162|
+----------+-----+

In [121]:
emp.groupBy('state','department').count().show()

+-----+----------+-----+
|state|department|count|
+-----+----------+-----+
|   CA|     Sales|   42|
|   CA| Marketing|   33|
|   NY|  Accounts|   34|
|   NY|     Sales|   27|
|   CA|   Finance|   35|
|   CA|  Accounts|   35|
|   CA|Purchasing|   32|
|   WA|        HR|   47|
|   AK|Purchasing|   30|
|   WA|  Accounts|   27|
|   WA|Purchasing|   38|
|   AK|     Sales|   38|
|   AK|  Accounts|   37|
|   WA| Marketing|   39|
|   LA|        HR|   41|
|   LA|     Sales|   35|
|   AK|        HR|   25|
|   LA|   Finance|   29|
|   AK|   Finance|   37|
|   LA|Purchasing|   45|
+-----+----------+-----+
only showing top 20 rows

In [122]:
emp.groupBy('department').agg(min('salary').alias('min_sal'),max('salary').alias('max_sal')).show()

+----------+-------+-------+
|department|min_sal|max_sal|
+----------+-------+-------+
|     Sales|   1103|   9982|
|        HR|   1013|   9982|
|   Finance|   1006|   9899|
|Purchasing|   1105|   9985|
| Marketing|   1031|   9974|
|  Accounts|   1007|   9890|
+----------+-------+-------+

In [129]:
av_bonus = emp.groupBy('state').avg('bonus').filter(emp.state=='NY').collect()[0][1]

In [132]:
emp.filter((emp.state=="NY") & (emp.department=="Finance") & (emp.bonus>av_bonus)).show()

+-----------+--------------------+----------+-----+------+---+-----+
|employee_id|       employee_name|department|state|salary|age|bonus|
+-----------+--------------------+----------+-----+------+---+-----+
|       1035|       Vivan Sifford|   Finance|   NY|  1129| 35| 1261|
|       1073|      Herder Gallman|   Finance|   NY|  1988| 31| 1402|
|       1082|          Nena Rocha|   Finance|   NY|  3417| 25| 1647|
|       1087|       Leif Lemaster|   Finance|   NY|  8642| 45| 1782|
|       1100|Ellingsworth Meli...|   Finance|   NY|  7845| 32| 1358|
|       1127|        Escoto Gilma|   Finance|   NY|  3426| 41| 1285|
|       1161|     Georgeanna Laub|   Finance|   NY|  2469| 26| 1679|
|       1175|     Durio Tenenbaum|   Finance|   NY|  2253| 42| 1684|
|       1180|       Juliana Grigg|   Finance|   NY|  8178| 42| 1617|
|       1215|        Tiffani Benz|   Finance|   NY|  1665| 41| 1969|
|       1220|          Nitz Ilana|   Finance|   NY|  2443| 50| 1342|
|       1342|   Phylicia Antonina|   Finance|   NY|  8626| 30| 1857|
|       1414|         Durio Janey|   Finance|   NY|  2992| 46| 1733|
|       1660|       Melissia Jere|   Finance|   NY|  9201| 21| 1533|
|       1737|      Yukiko Kreamer|   Finance|   NY|  7396| 20| 1332|
|       1738|      Nena Kensinger|   Finance|   NY|  8534| 41| 1610|
|       1815|      Antonina Ilana|   Finance|   NY|  2944| 28| 1718|
+-----------+--------------------+----------+-----+------+---+-----+

In [107]:
df_45 = employee.filter(employee.age>45)

In [109]:
df_45.write.options(header=True).csv('output45')

In [133]:
spark.stop()